name: Build and deploy a Go application to an Azure Web App

env:
  AZURE_WEBAPP_NAME: your-app-name  # Set this to your Azure Web App name
  GO_VERSION: 1.21.1  # Change to your desired Go version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build Go Application
        run: go build -o main

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Development'

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v2
        with:
          name: go-app
          path: .  # Download to the current directory

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: main  # Path to your Go binary
