name: Go CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1

    - name: Build
      run: go build -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@main
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/home/arioprima/apps/backend-go-letitbe
          git pull origin main
          git status
          go get .
          go build -v ./...
