name: Golang CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Build
        run: go build -o main

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "$YOUR_SSH_PRIVATE_KEY" > letitbe.pem
          chmod 600 letitbe.pem
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/known_hosts
          ssh-keyscan -H 103.127.97.105 >> $HOME/.ssh/known_hosts
          ssh -i letitbe.pem arioprima@103.127.97.105 "cd /var/www/golang/letitbe/letitbe/ && ./main"
        env:
          YOUR_SSH_PRIVATE_KEY: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOF8fffH3dlr9hLXLQ+LU1igzfg7ROJ/b0u9AUQ0P0aSsYYXsiUMWI+Yg0tuiSBNGYeZcDUiBAHZ33CeBK4o+mpTcPENN+EFbjlwyqME22jyvm2cwV/GZX9ZhemMZBuwg8RzKseVcYTkr/i3dY40ulAYLuWZU0G+uhYzDb1+KuDOeDHvDoVFj3qT3g3DRHzKw9hsYCtd4wXd9hoAqGLr2aFaHRK5OGJbV9Bb9/auAmv/2BicmDC2WzQL+oWNPfkbyG6pS+NSp2pHZsBq3bBMNs6NPRuuDdejDLtxvs3ZFh4HkRPMlvJnhSn6/6k0OD530L68l1/labkGYtxzhw6Psb
            -----END OPENSSH PRIVATE KEY-----

