name: Golang CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1 # Sesuaikan versi Go yang Anda gunakan

      - name: Build
        run: go build -o main

      - name: Archive artifacts
        run: tar -czf app.tar.gz main

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: go-app
          path: app.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest  # Gunakan runner Ubuntu atau sesuaikan dengan yang sesuai

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: go-app

      - name: Copy to Server
        run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${{ SSH_PRIVATE_KEY.SSH_PRIVATE_KEY }} app.tar.gz arioprima@103.127.97.105:/var/www/golang/letitbe/letitbe/

      - name: Extract on Server
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${{ SSH_PRIVATE_KEY.SSH_PRIVATE_KEY }} arioprima@103.127.97.105 "tar -xzf /var/www/golang/letitbe/letitbe/app.tar.gz -C /var/www/golang/letitbe/letitbe/"

      - name: Restart the Application
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${{ SSH_PRIVATE_KEY.SSH_PRIVATE_KEY }} arioprima@103.127.97.105 "systemctl restart your-app.service"
