name: Golang CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1 # Set the Go version you want to use

      - name: Build
        run: go build -o main

      - name: Archive artifacts
        run: tar -czf app.tar.gz main

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: go-app
          path: app.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: ${{ secrets.AZURE_WEBAPP_URL }} # Update with your environment variable

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: go-app
          path: ${{ runner.workspace }}/go-app

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ runner.workspace }}/go-app/app.tar.gz # Update the path to the artifact
