name: Golang CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: centos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Build
        run: go build -o main

  deploy:
    needs: build
    runs-on: centos-latest
    steps:
      - name: Deploy
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          scp -i deploy_key main arioprima@103.127.97.105:/var/www/golang/letitbe/letitbe/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
